using System;

namespace Aqua.Miscellaneous.Activation
{
    class ProductKeys
    {
        public static string[] EncryptedKeys = new string[] {
            "Cswc/.,5,./3Mj5 Lfo",
            "Cswc/.,5,./[@N`evh6",
            "Cswc/.,5,./-qWp[JiL",
            "Cswc/.,5,./yt4;UgQR",
            "Cswc/.,5,./07-qT6>2",
            "Cswc/.,5,./xLIcJUyl",
            "Cswc/.,5,./JTlYOmvN",
            "Cswc/.,5,./sNVrFPNe",
            "Cswc/.,5,./WS9H@EM[",
            "Cswc/.,5,./qjjDw?eg",
            "Cswc/.,5,./K9Dgp7V#",
            "Cswc/.,5,./1X?Ll#5G",
            "Cswc/.,5,./pPVpO94G",
            "Cswc/.,5,./Qoq;Id[;",
            "Cswc/.,5,./WMBZyH @",
            "Cswc/.,5,./b1M{KhXk",
            "Cswc/.,5,./kqtZ5qHu",
            "Cswc/.,5,./ j3G6wb6",
            "Cswc/.,5,./FuSO`tY6",
            "Cswc/.,5,./j>>h{[rf",
            "Cswc/.,5,./W#XE?0 [",
            "Cswc/.,5,./LbOTh9BI",
            "Cswc/.,5,./44rZ[I35",
            "Cswc/.,5,./QHb??tDi",
            "Cswc/.,5,./%EuH{9-2",
            "Cswc/.,5,./b?BKJcM9",
            "Cswc/.,5,./Q{FX;17W",
            "Cswc/.,5,./k1#CL#6.",
            "Cswc/.,5,./@#d;yIMt",
            "Cswc/.,5,./V.e5.ptg",
            "Cswc/.,5,./peHo7p0L",
            "Cswc/.,5,./un orCM`",
            "Cswc/.,5,./XYQ4>hoH",
            "Cswc/.,5,./6%Y0gWGw",
            "Cswc/.,5,./F 6WNg2@",
            "Cswc/.,5,./iFuHB?Jl",
            "Cswc/.,5,./b>#EyF##",
            "Cswc/.,5,./QR@Cr>uq",
            "Cswc/.,5,./;o?R5Js;",
            "Cswc/.,5,./10e`RD20",
            "Cswc/.,5,./n`dy@X;b",
            "Cswc/.,5,./u{?U3 XG",
            "Cswc/.,5,./p7SsWZ?w",
            "Cswc/.,5,./UW-f%ekg",
            "Cswc/.,5,./JXjb[ssr",
            "Cswc/.,5,./4e@Y5 0R",
            "Cswc/.,5,./-@f-mZvG",
            "Cswc/.,5,./1hd6wNr5",
            "Cswc/.,5,./y9fD{>cL",
            "Cswc/.,5,./C.soT[Q0",
            "Cswc/.,5,./J3QG.m7w",
            "Cswc/.,5,./uB7wXfD-",
            "Cswc/.,5,./d59F@[ r",
            "Cswc/.,5,./DOIs-j.H",
            "Cswc/.,5,./6uUM3-O@",
            "Cswc/.,5,./jJ73gZFG",
            "Cswc/.,5,./WxSrdr%7",
            "Cswc/.,5,./xVUdGTW{",
            "Cswc/.,5,./5lUjQ9C ",
            "Cswc/.,5,./n-IvVINZ",
            "Cswc/.,5,./rqlRR3k9",
            "Cswc/.,5,./UCXg06Pv",
            "Cswc/.,5,./vEqYynJ{",
            "Cswc/.,5,./GcYfU;7p",
            "Cswc/.,5,./%iS`7s[o",
            "Cswc/.,5,./`r@Tv6PD",
            "Cswc/.,5,./xkgNjCy5",
            "Cswc/.,5,./@u64s4pN",
            "Cswc/.,5,./L;p@Y34d",
            "Cswc/.,5,./lHX9jX-f",
            "Cswc/.,5,./>bNTvFFl",
            "Cswc/.,5,./wxFO527T",
            "Cswc/.,5,./vovW.@#T",
            "Cswc/.,5,./D-7RLYOq",
            "Cswc/.,5,./Y#-@Ft.s",
            "Cswc/.,5,./NiS4EuKe",
            "Cswc/.,5,./U5I%lgL@",
            "Cswc/.,5,./ofi`qSRl",
            "Cswc/.,5,./?2;th fw",
            "Cswc/.,5,./UWCEXEnm",
            "Cswc/.,5,./WNl>d9kU",
            "Cswc/.,5,./kBT#-9`4",
            "Cswc/.,5,./RstZ0I;b",
            "Cswc/.,5,./cnw6swbt",
            "Cswc/.,5,./6[v.XmMK",
            "Cswc/.,5,./NlT7[i>Z",
            "Cswc/.,5,./lt2PE;uI",
            "Cswc/.,5,./iD#7??NL",
            "Cswc/.,5,./oW7H9M-W",
            "Cswc/.,5,./9KY6q0pi",
            "Cswc/.,5,./GNVI0sqF",
            "Cswc/.,5,./4n9i?wJB",
            "Cswc/.,5,./7FJ-gFi?",
            "Cswc/.,5,./7xj3[#Lr",
            "Cswc/.,5,./p.#3DMmP",
            "Cswc/.,5,./Zb?FVVoD",
            "Cswc/.,5,./GWn-MwT[",
            "Cswc/.,5,./SdDh?QcG",
            "Cswc/.,5,./-onNVdfK",
            "Cswc/.,5,./4XIU5P0G",
            "Cswc/.,5,./b?iPBZ#;",
            "Cswc/.,5,./L1CKZchC",
            "Cswc/.,5,./;k3G6xY6",
            "Cswc/.,5,./6EQs-OTh",
            "Cswc/.,5,./[x>le6b1",
            "Cswc/.,5,./I>xVbL%B",
            "Cswc/.,5,./mciZG%rB",
            "Cswc/.,5,./1E[U9{tP",
            "Cswc/.,5,./KMRE-mjo",
            "Cswc/.,5,./hy1wDkpF",
            "Cswc/.,5,./O{QXsnGp",
            "Cswc/.,5,./`S1pQOeO",
            "Cswc/.,5,./;Rxe-DE2",
            "Cswc/.,5,./9%%ufBHE",
            "Cswc/.,5,./qCxFs0`e",
            "Cswc/.,5,./oJ t1.RH",
            "Cswc/.,5,./VvnIWyNs",
            "Cswc/.,5,./xwv3DRv.",
            "Cswc/.,5,./ITPEhGFZ",
            "Cswc/.,5,./ebe.W@9N",
            "Cswc/.,5,./c05GSXMn",
            "Cswc/.,5,./WQ%IqJ-R",
            "Cswc/.,5,./dOOPHqt.",
            "Cswc/.,5,./r4uoHVlX",
            "Cswc/.,5,./Q?GfdTtk",
            "Cswc/.,5,./gU%GwrT5",
            "Cswc/.,5,./LCjg9-M9",
            "Cswc/.,5,./YoOwHLbl",
            "Cswc/.,5,./ZK.wdncS",
            "Cswc/.,5,./Vow1GFT7",
            "Cswc/.,5,./IMXp>@Op",
            "Cswc/.,5,./UB@Pl%m;",
            "Cswc/.,5,./2Eq2fC7v",
            "Cswc/.,5,./n5x QO3[",
            "Cswc/.,5,./X2GgclKB",
            "Cswc/.,5,./JOTv?-@W",
            "Cswc/.,5,./b` jtDm2",
            "Cswc/.,5,./ lO3x1Jd",
            "Cswc/.,5,./BJLFHZ9V",
            "Cswc/.,5,./OWyFlQeJ",
            "Cswc/.,5,./3CR-pVJT",
            "Cswc/.,5,./lw;%gf[0",
            "Cswc/.,5,./M3T%gGJO",
            "Cswc/.,5,./oTVw`QU@",
            "Cswc/.,5,./Nmy3v6c-",
            "Cswc/.,5,./MFUxkW;i",
            "Cswc/.,5,./ToQ9YtcU",
            "Cswc/.,5,./ppD%m.3o",
            "Cswc/.,5,./tIPD`6Mx",
            "Cswc/.,5,./rL#CCJKs",
        };
    }
}
